### ISSUE TITLE
Problem with BNW

### ISSUE THREAD

**Issue by Eadrar** [AceHank/Epic-of-Fantasy#5]
Unable to use with mod Brave New World, appears: "Error: Qingbai Wares replaces National Treasury which does not exist!"
![Screenshot_20230223-173831](https://user-images.githubusercontent.com/126167932/220909415-f6f54328-d447-4b81-9c90-14c96e91f3a8.png)

**Comment by AceHank** [comment]
Yes, this mod can only be used with GnK and not created with BnW mod in mind.

**Comment by Eadrar** [comment]
I understand, just a few months ago both mods could be used together, most mods for new civilizations are also compatible with bnw. So it would be cool if this mod and bnw would be compatible if possible.

**Comment by AceHank** [comment]
That must be before the release of Fanrong Republic, if you can mod, you can change Fanrong Republic unique building yourself, I think that's the only thing preventing it working with BnW mod

**Comment by Eadrar** [comment]
I play unciv on phone so changing files is problematic for me. Thanks anyway
