### ISSUE TITLE
Merfolk Fishing boats missing option

### ISSUE THREAD

**Issue by ThePretzelcoatl** [AceHank/Epic-of-Fantasy#6]
I was trying to build a floating city with a fishing boat, but there was no option to do so. This was after discovering optics. Restarted the game and tried again, just to be sure, still didn't work.
Mod Error Report states that the option was removed, but replaced with the same option but consumes unit. Neither option was available for me.
Thoughts on a remedy? Perhaps I should rollback Gods & Kings or AbsoluteUnits?
![Screenshot_20230724-191916](https://github.com/AceHank/Epic-of-Fantasy/assets/140469442/5f6e54b2-9d18-4b4a-98e3-261133708bfd)
![Screenshot_20230724-191902](https://github.com/AceHank/Epic-of-Fantasy/assets/140469442/22ed97ad-3dec-48a4-b2a6-710ac625e8bf)

**Comment by AceHank** [comment]
Fixed! Thank you for the feedback. And please report again if you find another problem!
