### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by sls1005** [AceHank/Epic-of-Fantasy#8]
It seems that there is something wrong with the encoding of [`Nations.json`](https://github.com/AceHank/Epic-of-Fantasy/blob/main/jsons/Nations.json), which doesn't happen in pervious versions. For example, `ū` (U+016B) becomes `Å«` in this version.

### Explanation

It's assumed that the original encoding is UTF-8. In UTF-8, `ū` is encoded as `\xc5\xab`. If the file editor incorrectly assumes Latin-1 or a similar encoding when opening the file, it will be reinterpreted as `Å«`, because that's what `\xc5\xab` means in that encoding. And if the file is again saved using UTF-8 after that, it's `Å«` that will be written back into the file (as two unicode characters). It's especially likely to happen if there was originally a BOM (byte-order-mark) and was removed before the file is opened again by the file editor.

### Solution

<strike>Open this file with an editor by assuming UTF-8 as the file encoding, and then save it with Latin-1 (Not sure) as the encoding. (It's also possible that it should be Code Page 1252 rather than Latin-1.) Then re-open the saved file by assuming UTF-8 (Yes, UTF-8) as the encoding. The characters should then be correct. Then save it again as UTF-8, use a BOM if required.</strike>

**Comment by AceHank** [comment]
Ah, I see the problem now, I will try to fix it, if nothing works, I will just replace `ū` with normal `u`. Thanks for reporting! It will go live with the next update!

**Comment by sls1005** [comment]
I'm working on it. And I think it is more complex than that. When I open the file with UTF-8, I see `ū` but also unknown characters (something that look like `<?>`). When I instead use CP1252, I don't see those unknown characters, but names looks strange. The first case is closer to the situation in the game. It's also known that the game uses UTF-8.

**Comment by sls1005** [comment]
I fixed it in <https://github.com/sls1005/Epic-of-Fantasy/tree/dev-1>.

It seems that the encoding of the latest version of the file is still UTF-8, but `ā` is replaced by `\xc4\x3f` (the byte sequence represented by this string) for some unknown reason (with other characters unchanged), which caused the whole file to be displayed in Latin-1 rather than UTF-8 to avoid unprintable characters.

**Comment by AceHank** [comment]
> I fixed it in https://github.com/sls1005/Epic-of-Fantasy/tree/dev-1.
> 
> It seems that the encoding of the latest version of the file is still UTF-8, but `ā` is replaced by `\xc4\x3f` (the byte sequence represented by this string) for some unknown reason (with other characters unchanged), which caused the whole file to be displayed in Latin-1 rather than UTF-8 to avoid unprintable characters.

Thank you very much for the help! Can I merge it into main? Or will you do a PR?

And if I may know, because I am not a tech savvy, what could possibly make this happen? Is it something that I can prevent?

**Comment by sls1005** [comment]
>Or will you do a PR?

I'll do.

>what could possibly make this happen? Is it something that I can prevent?

Don't know, but I have some assumptions.

The character `ā` is encoded in UTF-8 as `\xc4\x81`. Why would it be changed to `\xc4\x3f`? In Latin-1, `\xc4` is `Ä`; `\x81` is undefined (not a control character; just undefined); `\x3f` is `?` (question mark), hence, as I mentioned before, if you open the file with an editor which assumes Latin-1, `\xc4\x81` might be displayed as `Ä?`, (where `?` means unknown, while the correct code-point of `?` is `0x3f` rather than `0x81`), and if you copy and paste it somewhere else, it might be changed to `Ä` followed by a normal question mark '`?`' (`\x3f`), so it would become `\xc4\x3f`; and then when the file is re-opened as UTF-8, `\x3f` is still '`?`' (U+003F, question mark), but `\xc4` in its own turn becomes the unknown character we see. The reason is that, in UTF-8, the byte `0xc4` without specific byte sequence following is an incomplete chatcter, while `Ä` (U+00C4) is encoded as `\xc3\x84`.

As for why it doesn't happen to ī and ū (which are still correct in game): the character `ū` is encoded in UTF-8 as `\xc5\xab`. In Latin-1, `\xc5` is `Ä`; `\xab` is `«`; both are displayable (though very strange). The character `ī` is encoded in UTF-8 as `\xc4\xab`. In Latin-1, `\xc4` is `Ä`; '\xab', as mentioned above, is `«`. This might be the reason why they are unaffected when converted back.

This not only applys to Latin-1, but also some other forms of extened ASCII. In Shift-JIS, `\xc4` is `ﾄ` (halfwidth katakana To); `\xc5` is `ﾅ` (halfwidth katakana Na); `\x3f` is `?` (question mark); `\x81` is an incomplete chatacter. There're also encodings that can't decode a single `\xc4` or `\xc5`, but I think they're not involved.

As for how to prevent it: one thing that is important is to always mind the encoding we use to open and save files. Another is to be extra careful when using characters that are not included in (non-extended) ASCII. Some people would put a BOM (byte-order-mark) in their source files to enable them to use non-ASCII characters without facing the encoding issue, but it also can also cause other problems. I'll try to do some tests with BOM in the next few days. I also remember that the European specification of JSON allows the use of UTF-16–based escape sequences (while the file itself is still ASCII or UTF-8), so I'll also test about it.

The base game also uses `ü`, so it should be no wrong to use those extended characters. The only limitation I know is that we should use precomposed unicode characters (like `ü` instead of u +   ̈), or they would be displayed separately, because the diacritics support is unlikely to be enabled for English.

**Comment by AceHank** [comment]
> > Or will you do a PR?
> 
> I'll do.
>
> As for how to prevent it: one thing that is important is to always mind the encoding we use to open and save files. Another is to be extra careful when using characters that are not included in (non-extended) ASCII. Some people would put a BOM (byte-order-mark) in their source files to enable them to use non-ASCII characters without facing the encoding issue, but it also can also cause other problems. I'll try to do some tests with BOM in the next few days. I also remember that the European specification of JSON allows the use of UTF-16–based escape sequences (while the file itself is still ASCII or UTF-8), so I'll also test about it.

Ok, I will wait for the PR! Thank you!

And I always use Notepad++, I will make sure to double check when using these kind of characters!
